/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1Gxv5jdM0V7
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"

export function Component() {
  return (
    <Card key="1" className="mx-auto max-w-sm">
      <CardHeader>
        <CardTitle>Upload Video</CardTitle>
        <CardDescription>Choose a video from your device to upload</CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col gap-4 bg-gray-100 dark:bg-gray-850">
        <div className="grid gap-2">
          <Button as="label" className="w-full" htmlFor="file">
            Select Video
            <Input className="sr-only" id="file" type="file" />
          </Button>
          <Progress value={0} />
        </div>
        <div className="grid gap-2">
          <Input placeholder="Video Title" />
          <Input placeholder="Description" type="textarea" />
        </div>
        <Button className="mt-auto">Upload</Button>
      </CardContent>
    </Card>
  )
}
